# Generated by Django 3.0.8 on 2020-08-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProductDescription',
            new_name='Description',
        ),
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Image',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='description',
            table='descriptions',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
    ]
