# Generated by Django 3.0.8 on 2020-08-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200822_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_image',
            new_name='image_url',
        ),
    ]
