# Generated by Django 3.0.8 on 2020-08-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200822_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
