# Generated by Django 3.0.8 on 2020-08-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_html'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Html',
            new_name='HtmlTag',
        ),
        migrations.AlterModelTable(
            name='htmltag',
            table='html_tags',
        ),
    ]
