# Generated by Django 3.0.8 on 2020-08-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200826_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmltag',
            old_name='html_tag',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
