# Generated by Django 3.1 on 2020-08-21 20:29

from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('birthdate', models.DateField(max_length=16)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256, validators=[user.validators.password_validation_function])),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[user.validators.phone_number_validation_function])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gender')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='User_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endrolled_giftcard', models.PositiveIntegerField()),
                ('coupon', models.PositiveIntegerField()),
                ('inquiry_history', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_information',
            },
        ),
    ]
