# Generated by Django 3.0.8 on 2020-08-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_image',
        ),
    ]
