# Generated by Django 3.1 on 2020-08-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cart_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
